services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat_server
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    ports:
      - "${SERVER_PORT:-8080}:8080"
    depends_on:
      - db
    networks:
      - chat_network

  db:
    image: postgres:15-alpine
    container_name: chat_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge

volumes:
  postgres_data:
